<?php
$sLangName = "Deutsch";

$aLang = array(
    'charset' => 'UTF-8',

    'WMDK_ARTICLE_VARIANT_MAPPING' => 'Mapping',

    'WMDK_UNMAPPED' => 'Ungemappt oder löschen',
    'KUSSIN_FF_EXPORT_QUEUE_ARTICLE_MONITOR_OPEN' => 'Im FACT Finder Monitor anzeigen',
    'KUSSIN_FF_EXPORT_QUEUE_ARTICLE_MONITOR_TITLE' => 'Elternartikel und Varianten im FACT Finder Monitor in einem neuen Tab anzeigen',
    'KUSSIN_FF_EXPORT_QUEUE_OXID_FILTER_HINT' => 'Mehrere vollständige OXIDs mit Komma, Leerzeichen, Semikolon, Pipe oder OR trennen',
    'mxkussin' => 'Kussin',
    'wmdkffexport_monitor' => 'KUSSIN | FACT Finder Export Queue - Monitor',
    'WMDK_FF_MONITOR_TITLE' => 'KUSSIN | FACT Finder Export Queue - Monitor',
    'WMDK_FF_MONITOR_INTRO' => 'Queue-Status prüfen, Datensätze filtern und sortieren, vollständig als CSV exportieren oder ausgewählte Artikel über alle Channels, Shops und Sprachen erneut zur Verarbeitung markieren.',
    'WMDK_FF_MONITOR_LOADING' => 'Daten werden verarbeitet …',
    'WMDK_FF_MONITOR_WAITING' => 'Artikel warten auf Aktualisierung',
    'WMDK_FF_MONITOR_FILTERED' => 'gefilterte Queue-Datensätze',
    'WMDK_FF_MONITOR_PAGE' => 'Seite',
    'WMDK_FF_MONITOR_ETA' => 'Voraussichtlich fertig',
    'WMDK_FF_MONITOR_ETA_PREFIX' => 'ca.',
    'WMDK_FF_MONITOR_ETA_DONE' => 'Fertig',
    'WMDK_FF_MONITOR_ETA_HOUR' => 'Std.',
    'WMDK_FF_MONITOR_ETA_MINUTE' => 'Min.',
    'WMDK_FF_MONITOR_ETA_RECORDS' => 'wartende Artikel',
    'WMDK_FF_MONITOR_ETA_BASIS' => 'bei einem Lauf alle 2 Minuten',
    'WMDK_FF_MONITOR_FILTER' => 'Filter anwenden',
    'WMDK_FF_MONITOR_CLEAR_FILTER' => 'Filter zurücksetzen',
    'WMDK_FF_MONITOR_EXPORT' => 'Gefilterte Datensätze als CSV exportieren',
    'WMDK_FF_MONITOR_ALL' => 'Alle',
    'WMDK_FF_MONITOR_TRUE' => 'Ja',
    'WMDK_FF_MONITOR_FALSE' => 'Nein',
    'WMDK_FF_MONITOR_PREVIEW_COLUMN' => 'Vorschau',
    'WMDK_FF_MONITOR_NOT_FILTERABLE' => 'Numerisches Feld – nicht filterbar',
    'WMDK_FF_MONITOR_PREVIEW' => 'Artikelvorschau öffnen',
    'WMDK_FF_MONITOR_EDIT_ARTICLE' => 'Artikel-Stamm in einem neuen Tab öffnen',
    'WMDK_FF_MONITOR_NO_RESULTS' => 'Keine Queue-Datensätze gefunden.',
    'WMDK_FF_MONITOR_SELECT_ALL' => 'Alle Datensätze dieser Seite auswählen',
    'WMDK_FF_MONITOR_RESET_SELECTED' => 'Ausgewählte Artikel vollständig zurücksetzen',
    'WMDK_FF_MONITOR_RESET_CONFIRM' => 'Alle Queue-Datensätze der ausgewählten OXIDs über sämtliche Channels, Shops und Sprachen zurücksetzen?',
    'WMDK_FF_MONITOR_RESET_SUCCESS' => 'Zurückgesetzt (Artikel / Queue-Datensätze)',
    'WMDK_FF_MONITOR_RESET_EMPTY' => 'Es wurden keine Artikel ausgewählt.',
);
