<?php
$sLangName = "English";

$aLang = array(
    'charset' => 'UTF-8',

    'WMDK_ARTICLE_VARIANT_MAPPING' => 'Mapping',

    'WMDK_UNMAPPED' => 'Unmapped or Delete',
    'KUSSIN_FF_EXPORT_QUEUE_ARTICLE_MONITOR_OPEN' => 'Show in FACT Finder Monitor',
    'KUSSIN_FF_EXPORT_QUEUE_ARTICLE_MONITOR_TITLE' => 'Show parent article and variants in the FACT Finder Monitor in a new tab',
    'KUSSIN_FF_EXPORT_QUEUE_OXID_FILTER_HINT' => 'Separate multiple complete OXIDs with commas, spaces, semicolons, pipes, or OR',
    'mxkussin' => 'Kussin',
    'wmdkffexport_monitor' => 'KUSSIN | FACT Finder Export Queue - Monitor',
    'WMDK_FF_MONITOR_TITLE' => 'KUSSIN | FACT Finder Export Queue - Monitor',
    'WMDK_FF_MONITOR_INTRO' => 'Review queue status, filter and sort records, export all matching data as CSV, or requeue selected articles across every channel, shop, and language.',
    'WMDK_FF_MONITOR_LOADING' => 'Processing data …',
    'WMDK_FF_MONITOR_WAITING' => 'articles waiting for an update',
    'WMDK_FF_MONITOR_FILTERED' => 'filtered queue records',
    'WMDK_FF_MONITOR_PAGE' => 'Page',
    'WMDK_FF_MONITOR_ETA' => 'Estimated completion',
    'WMDK_FF_MONITOR_ETA_PREFIX' => 'approx.',
    'WMDK_FF_MONITOR_ETA_DONE' => 'Complete',
    'WMDK_FF_MONITOR_ETA_HOUR' => 'h',
    'WMDK_FF_MONITOR_ETA_MINUTE' => 'min',
    'WMDK_FF_MONITOR_ETA_RECORDS' => 'pending articles',
    'WMDK_FF_MONITOR_ETA_BASIS' => 'at one run every 2 minutes',
    'WMDK_FF_MONITOR_FILTER' => 'Apply filters',
    'WMDK_FF_MONITOR_CLEAR_FILTER' => 'Clear filters',
    'WMDK_FF_MONITOR_EXPORT' => 'Export filtered records as CSV',
    'WMDK_FF_MONITOR_ALL' => 'All',
    'WMDK_FF_MONITOR_TRUE' => 'Yes',
    'WMDK_FF_MONITOR_FALSE' => 'No',
    'WMDK_FF_MONITOR_PREVIEW_COLUMN' => 'Preview',
    'WMDK_FF_MONITOR_NOT_FILTERABLE' => 'Numeric field – not filterable',
    'WMDK_FF_MONITOR_PREVIEW' => 'Open article preview',
    'WMDK_FF_MONITOR_EDIT_ARTICLE' => 'Open article master data in a new tab',
    'WMDK_FF_MONITOR_NO_RESULTS' => 'No queue records found.',
    'WMDK_FF_MONITOR_SELECT_ALL' => 'Select all records on this page',
    'WMDK_FF_MONITOR_RESET_SELECTED' => 'Fully reset selected articles',
    'WMDK_FF_MONITOR_RESET_CONFIRM' => 'Reset every queue record for the selected OXIDs across all channels, shops, and languages?',
    'WMDK_FF_MONITOR_RESET_SUCCESS' => 'Reset (articles / queue records)',
    'WMDK_FF_MONITOR_RESET_EMPTY' => 'No articles were selected.',
);
